### PR TITLE
Made minor UI changes to quick survey and home screen

### PR DESCRIPTION
**Pull request by coverney**
Relevant Trello cards
- https://trello.com/c/bA06G6tL
- https://trello.com/c/ZB5oJriP
- https://trello.com/c/RvHYw5ng
- https://trello.com/c/eL0hBy5b
- https://trello.com/c/jmNLl8Ez

### CODE REVIEW

**Comment by Enmoren** [comment]
https://github.com/santosfamilyfoundation/RuinaMain/commit/84a2f1330d89cc622b55c68b36736bee67dc4725#diff-02f7938e69b4dcfeef4a6397cb536ee31b69f37536b5f778dae4f74dd67da9d6L117-L123

I think the delete section still exists here.

**Comment by coverney** [comment]
> [https://github.com/santosfamilyfoundation/RuinaMain/commit/84a2f1330d89cc622b55c68b36736bee67dc4725#diff-02f7938e69b4dcfeef4a6397cb536ee31b69f37536b5f778dae4f74dd67da9d6L117-L123](url)
> I think the delete section still exists here.

Somehow the link didn't work for me. But none of my changes involved changing the delete section so that's why it's probably the same. If I change it, then it would conflict with your changes.

**Comment by Enmoren** [comment]
Yeah, That part is conflicting with my changes, and I was not sure why you decide to change it. We can talk about it on Friday.

**Comment by coverney** [comment]
> Yeah, That part is conflicting with my changes, and I was not sure why you decide to change it. We can talk about it on Friday.

wait what did I change? Lol, I don't remember editing the delete section stuff. Okay, let's share screen and figure this out on Friday. Got to enjoy our break! :)

**Pull request merged**
