### PR TITLE
Change story reducer and multiple question type to support dependency feature

### PR DESCRIPTION
**Pull request by Enmoren**
- Change story reducer and story action to push all user input into story reducer. This is needed to support dependency checking across multiple sections. 
- Modify different question components to check if a component needs to be rendered based on the user's answers stored in story reducer. 
Refers to this Trello card: https: //trello.com/c/F7D6iMY8

### CODE REVIEW

**Review by xieruishen — CHANGES_REQUESTED** [review]
Overall looks great. There is one minor issue. If I first select "no" for vehicle hazardous material question and go to the driver, it would properly hide the respective questions. but if i then change it to "yes", the corresponding questions in driver section still wouldn't show up. Not sure why

**Comment by Enmoren** [comment]
@xieruishen I was not able to produce the issue. Does the status bar turn green when you changed it to "Yes"?

**Comment by Enmoren** [comment]
Nvm my previous comment, just figure out the bug and update the code accordingly, you can find my changes [here](https://github.com/santosfamilyfoundation/RuinaMain/pull/83/commits/7c8f321f446671da713de5300a3f2f92c4b52fd7). Let me know if this one got pass on your side.

**Comment by xieruishen** [comment]
> Nvm my previous comment, just figure out the bug and update the code accordingly, you can find my changes [here](https://github.com/santosfamilyfoundation/RuinaMain/pull/83/commits/7c8f321f446671da713de5300a3f2f92c4b52fd7). Let me know if this one got pass on your side.

Just tested the change, yup it all works on my side too. Thanks enmo this is great! :)

**Review by xieruishen — APPROVED** [review]

**Pull request merged**
