### PR TITLE
Setting up for http request from front end using axios

### PR DESCRIPTION
**Pull request by Enmoren**

### CODE REVIEW

**Comment by coverney** [comment]
Looks great! Just need to write a test and resolve the merge conflict!

**Review by coverney — APPROVED** [review]

**Comment by Enmoren** [comment]
I restructured ReportToDatabase.js. I will finish writing test later!

**Comment by xieruishen** [comment]
Why does the changed files include changes from both email and save to device feature? Something might went wrong when the merge happen

**Comment by xieruishen** [comment]
Here is a more thorough list for files/changes include that both cassandra and I's changes. For example, these files `SaveToDevice.js`, `EmailFinalReport.js`, `saveToDeviceScreen.js`, `setupTest.js`. `saveToDeviceScreen.js`, `saveToDeviceScreen.js`, all the font files are re-added, changes in `android_build.gradle`, `AndroidManifext.xml`, `Apps-test.js` all the files in `ios/` from save-to-device changes are re-added. In `FinalReport.js` it has both the database changes and the reformatting as new changes. In `appNavigator.js` it also has changes from saveToDevice and your new changes added as new changes. Same with `package.json`. Also i think you might mistakenly added an old local version of `FinalReport.js` -> `finalreport_dev.js` You might want to move you local changes somewhere else, repull from dev and add in changes that are specific to database.

**Comment by Enmoren** [comment]
Again!

**Comment by coverney** [comment]
All the feature worked so I am merging this in

**Pull request merged**
